spring:

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true



